In [ ]:
ANS 1: Yes, there is a difference in the data type of the variables list_ and array_list. The list_ variable is a Python
list, while the array_list variable is a NumPy array.
We can use type() function to print the data types of both variables.Here's a code to do that

In [1]:
import numpy as np

list_ =['1','2','3','4','5']
array_list = np.array(object=list_)

print("Data type of list_:" , type(list_))
print("Data type of array_list:" , type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
ANS 2:

In [2]:
import numpy as np

list_ = ['1','2','3','4','5']
array_list  = np.array(object=list_)

print("Data type of each element in list_:")
for i in list_:
    print(type(i))
    
print("Data type of each element in array_list:")
for i in array_list:
    print(type(i))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
ANS 3: Yes,there will be a difference in the data type of the elements present in the varaibles list_ and array_list 
after using the 'dtype = int' parameter while creating the NumPy array 'array_list' will be converted to integers.

In [3]:
import numpy as np

list_ = ['1','2','3','4','5']
array_list = np.array(object = list_ , dtype=int)
print("Data type of each element in list_:")
for i in list_:
    print(type(i))
    
print("Data type of each element in array_list:")
for i in array_list:
    print(type(i))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
ANS 4:

In [4]:
import numpy as np
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object=num_list)
shape = num_array.shape
size = num_array.size
print("Shape of num list:" , shape)
print("Size of num array:" , size)

Shape of num list: (2, 3)
Size of num array: 6


In [ ]:
ANS 5 :

In [5]:
import numpy as np

zero_matrix = np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ANS 6:

In [7]:
import numpy as np

idy_matrix = np.eye(5)
print(idy_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
